project:
  type: website
  
execute:
  freeze: auto

website:
  title: "SKS"
  description: "Personal Protfolio of Shafayet Khan Shafee"
  favicon: /assets/images/logo.svg
  image: /assets/images/bw_propic.jpeg
  site-url: https://shafayetshafee.github.io
  repo-url: https://github.com/shafayetShafee/shafayetShafee.github.io
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    border: true
    left: |
      Built with [{{< iconify logos:r-lang title="R Logo" label="R Logo" >}}](https://www.r-project.org/)  & [Quarto](https://quarto.org).
    center: |
      Copyright &copy; 2025 Shafayet Khan Shafee
    right: |
      License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0)
  search: 
    location: navbar
    type: overlay
  navbar:
    title: "SKU"
    search: true
    logo: assets/images/logo.svg
    logo-alt: "Shafayet Khan Shafee logo"
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
        
    right:
      - icon: mastodon
        href: https://fosstodon.org/@shafayet_shafee
      - icon: bluesky
        href: https://bsky.app/profile/kshafayet.bsky.social
      - icon: twitter
        href: https://x.com/shafayet_shafee
      - icon: linkedin
        href: https://www.linkedin.com/in/shafayetshafee/
      - icon: github
        href: https://github.com/shafayetShafee
      - text: '{{< iconify fa6-brands:google-scholar >}}'
        href: https://scholar.google.com/citations?user=GSgDEx0AAAAJ&hl=en
      - text: '{{< iconify academicons:orcid >}}'
        href: https://orcid.org/0009-0002-8021-3788
      - icon: envelope-at-fill
        href: mailto:sshafee@isrt.ac.bd
        
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    page-layout: full
    respect-user-color-scheme: true
    email-obfuscation: javascript
    link-external-newwindow: true
    lightbox: true



