project:
  type: website
  render:
    - "*.qmd"
    - "!uv-cache/"
  
execute:
  freeze: auto

website:
  title: "SKS"
  description: "Personal Protfolio of Shafayet Khan Shafee"
  favicon: /assets/images/logo.svg
  image: /assets/images/bw_propic.jpeg
  site-url: https://shafayetshafee.github.io
  repo-url: https://github.com/shafayetShafee/shafayetShafee.github.io
  repo-link-target: "_blank"
  open-graph: true
  twitter-card: true
  page-footer:
    border: true
    left: |
      Built with [{{< iconify logos:r-lang title="R Logo" label="R Logo" >}}](https://www.r-project.org/)  & [Quarto](https://quarto.org).
    center: |
      Copyright &copy; 2025 Shafayet Khan Shafee
    right: |
      License: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0)
  search:
    location: navbar
    type: overlay
  navbar:
    title: "SKS"
    search: true
    logo: assets/images/logo.svg
    logo-alt: "Shafayet Khan Shafee logo"
    left:
      - href: index.qmd
        text: About
      - href: publications/index.qmd
        text: Publications
        
    right:
      - icon: mastodon
        href: https://fosstodon.org/@shafayet_shafee
        target: "_blank"
      - icon: bluesky
        href: https://bsky.app/profile/kshafayet.bsky.social
        target: "_blank"
      - icon: twitter-x
        href: https://x.com/shafayet_shafee
        target: "_blank"
      - icon: linkedin
        href: https://www.linkedin.com/in/shafayetshafee/
        target: "_blank"
      - icon: github
        href: https://github.com/shafayetShafee
        target: "_blank"
      - text: '{{< iconify fa6-brands:google-scholar >}}'
        href: https://scholar.google.com/citations?user=GSgDEx0AAAAJ&hl=en
        target: "_blank"
      - text: '{{< iconify academicons:orcid >}}'
        href: https://orcid.org/0009-0002-8021-3788
        target: "_blank"
      - icon: envelope-at-fill
        href: mailto:sshafee@isrt.ac.bd
        
format:
  html:
    theme:
      light: 
        - cosmo
        - brand
        - assets/stylesheets/theme.scss
      dark: 
        - solar
        - brand
        - assets/stylesheets/theme.scss
    page-layout: full
    respect-user-color-scheme: true
    email-obfuscation: javascript
    link-external-newwindow: true
    css:
      - "https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css"
      - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    include-after-body: 
      - file: assets/scripts/remove-empty-title-meta.html



